---
# prepare run `sudo mkdir -p /srv/l2-essence/mysql /srv/l2-essence/login /srv/l2-essence/game`

networks:
  l2-net:
    name: l2-net
    attachable: true

volumes:
  l2-mysql:
    name: l2-mysql
    driver_opts:
      type: local
      device: '/srv/l2-essence/mysql'
      o: bind
  l2-login:
    name: l2-login
    driver_opts:
      type: local
      device: '/srv/l2-essence//login'
      o: bind
  l2-game:
    name: l2-game
    driver_opts:
      type: local
      device: '/srv/l2-essence/game'
      o: bind

services:
  game:
    image: "ghcr.io/rootshell-coder/l2-game-server:latest"
    ports:
      - "7777:7777"
      - "2106:2106"
    networks:
      - "l2-net"
    volumes:
      - "l2-mysql:/var/lib/mysql/"
      - "l2-login:/app/login"
      - "l2-game:/app/game"
    restart: "always"
